// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_9Uq0_fDdO_6M4Lh_8MvdPIyxqfApHiQ',
    appId: '1:804178994309:web:f525bb6e153170f8f275ec',
    messagingSenderId: '804178994309',
    projectId: 'flutter-application-1-c48df',
    authDomain: 'flutter-application-1-c48df.firebaseapp.com',
    storageBucket: 'flutter-application-1-c48df.firebasestorage.app',
    measurementId: 'G-79F5P16QT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBU50HYE6ff-Y2hNLba94fbiOsrkZPzs',
    appId: '1:804178994309:android:bfcde0ea790a2e73f275ec',
    messagingSenderId: '804178994309',
    projectId: 'flutter-application-1-c48df',
    storageBucket: 'flutter-application-1-c48df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2_Hkk-WQchtVrrvrOj12qUXnbTm56P34',
    appId: '1:804178994309:ios:5d979a6d9db71627f275ec',
    messagingSenderId: '804178994309',
    projectId: 'flutter-application-1-c48df',
    storageBucket: 'flutter-application-1-c48df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2_Hkk-WQchtVrrvrOj12qUXnbTm56P34',
    appId: '1:804178994309:ios:5d979a6d9db71627f275ec',
    messagingSenderId: '804178994309',
    projectId: 'flutter-application-1-c48df',
    storageBucket: 'flutter-application-1-c48df.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_9Uq0_fDdO_6M4Lh_8MvdPIyxqfApHiQ',
    appId: '1:804178994309:web:f7a6e6d66a2cec71f275ec',
    messagingSenderId: '804178994309',
    projectId: 'flutter-application-1-c48df',
    authDomain: 'flutter-application-1-c48df.firebaseapp.com',
    storageBucket: 'flutter-application-1-c48df.firebasestorage.app',
    measurementId: 'G-CLL3HH5R6Y',
  );

}